package security

import (
	"time"

	"github.com/google/uuid"
)

// AlertType defines the type of security alert
type AlertType string

const (
	AlertTypeSOS          AlertType = "SOS"
	AlertTypeMedical      AlertType = "MEDICAL"
	AlertTypeFire         AlertType = "FIRE"
	AlertTypeTheft        AlertType = "THEFT"
	AlertTypeViolence     AlertType = "VIOLENCE"
	AlertTypeLostChild    AlertType = "LOST_CHILD"
	AlertTypeSuspicious   AlertType = "SUSPICIOUS"
	AlertTypeCrowdControl AlertType = "CROWD_CONTROL"
	AlertTypeOther        AlertType = "OTHER"
)

// AlertSeverity defines the severity level of an alert
type AlertSeverity string

const (
	AlertSeverityLow      AlertSeverity = "LOW"
	AlertSeverityMedium   AlertSeverity = "MEDIUM"
	AlertSeverityHigh     AlertSeverity = "HIGH"
	AlertSeverityCritical AlertSeverity = "CRITICAL"
)

// AlertStatus defines the current status of an alert
type AlertStatus string

const (
	AlertStatusPending    AlertStatus = "PENDING"
	AlertStatusAcknowledged AlertStatus = "ACKNOWLEDGED"
	AlertStatusInProgress AlertStatus = "IN_PROGRESS"
	AlertStatusResolved   AlertStatus = "RESOLVED"
	AlertStatusCancelled  AlertStatus = "CANCELLED"
)

// Alert represents a security alert
type Alert struct {
	ID            uuid.UUID     `json:"id" gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	FestivalID    uuid.UUID     `json:"festivalId" gorm:"type:uuid;not null;index"`
	UserID        *uuid.UUID    `json:"userId,omitempty" gorm:"type:uuid;index"`
	Type          AlertType     `json:"type" gorm:"not null;default:'OTHER'"`
	Severity      AlertSeverity `json:"severity" gorm:"not null;default:'MEDIUM'"`
	Status        AlertStatus   `json:"status" gorm:"not null;default:'PENDING'"`
	Title         string        `json:"title" gorm:"not null"`
	Description   string        `json:"description"`
	Location      AlertLocation `json:"location" gorm:"type:jsonb;default:'{}'"`
	ContactPhone  string        `json:"contactPhone,omitempty"`
	AssignedTo    *uuid.UUID    `json:"assignedTo,omitempty" gorm:"type:uuid;index"`
	AcknowledgedAt *time.Time   `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *uuid.UUID   `json:"acknowledgedBy,omitempty" gorm:"type:uuid"`
	ResolvedAt    *time.Time    `json:"resolvedAt,omitempty"`
	ResolvedBy    *uuid.UUID    `json:"resolvedBy,omitempty" gorm:"type:uuid"`
	Resolution    string        `json:"resolution,omitempty"`
	Metadata      AlertMetadata `json:"metadata" gorm:"type:jsonb;default:'{}'"`
	CreatedAt     time.Time     `json:"createdAt"`
	UpdatedAt     time.Time     `json:"updatedAt"`
}

func (Alert) TableName() string {
	return "security_alerts"
}

// AlertLocation represents the GPS coordinates and location details
type AlertLocation struct {
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Accuracy    float64 `json:"accuracy,omitempty"`
	Zone        string  `json:"zone,omitempty"`
	Description string  `json:"description,omitempty"`
}

// AlertMetadata contains additional metadata for alerts
type AlertMetadata struct {
	DeviceInfo   string   `json:"deviceInfo,omitempty"`
	AppVersion   string   `json:"appVersion,omitempty"`
	Attachments  []string `json:"attachments,omitempty"`
	Tags         []string `json:"tags,omitempty"`
	Priority     int      `json:"priority,omitempty"`
	AutoGenerated bool    `json:"autoGenerated,omitempty"`
}

// SecurityZone represents a defined security zone within a festival
type SecurityZone struct {
	ID          uuid.UUID    `json:"id" gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	FestivalID  uuid.UUID    `json:"festivalId" gorm:"type:uuid;not null;index"`
	Name        string       `json:"name" gorm:"not null"`
	Description string       `json:"description"`
	Type        ZoneType     `json:"type" gorm:"not null;default:'GENERAL'"`
	Coordinates []Coordinate `json:"coordinates" gorm:"type:jsonb;default:'[]'"`
	Capacity    int          `json:"capacity,omitempty"`
	AlertLevel  AlertSeverity `json:"alertLevel,omitempty" gorm:"default:'LOW'"`
	IsActive    bool         `json:"isActive" gorm:"default:true"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

func (SecurityZone) TableName() string {
	return "security_zones"
}

// ZoneType defines the type of security zone
type ZoneType string

const (
	ZoneTypeGeneral   ZoneType = "GENERAL"
	ZoneTypeVIP       ZoneType = "VIP"
	ZoneTypeStage     ZoneType = "STAGE"
	ZoneTypeCamping   ZoneType = "CAMPING"
	ZoneTypeParking   ZoneType = "PARKING"
	ZoneTypeEntrance  ZoneType = "ENTRANCE"
	ZoneTypeMedical   ZoneType = "MEDICAL"
	ZoneTypeRestricted ZoneType = "RESTRICTED"
)

// Coordinate represents a GPS coordinate point
type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// SOSRequest represents a request to create an SOS alert
type SOSRequest struct {
	Message     string        `json:"message"`
	Location    AlertLocation `json:"location" binding:"required"`
	ContactPhone string       `json:"contactPhone,omitempty"`
}

// CreateAlertRequest represents a request to create a security alert
type CreateAlertRequest struct {
	Type         AlertType     `json:"type" binding:"required"`
	Severity     AlertSeverity `json:"severity"`
	Title        string        `json:"title" binding:"required"`
	Description  string        `json:"description"`
	Location     AlertLocation `json:"location"`
	ContactPhone string        `json:"contactPhone,omitempty"`
	Metadata     AlertMetadata `json:"metadata,omitempty"`
}

// UpdateAlertRequest represents a request to update an alert
type UpdateAlertRequest struct {
	Status      *AlertStatus   `json:"status,omitempty"`
	Severity    *AlertSeverity `json:"severity,omitempty"`
	AssignedTo  *uuid.UUID     `json:"assignedTo,omitempty"`
	Description *string        `json:"description,omitempty"`
	Resolution  *string        `json:"resolution,omitempty"`
}

// ResolveAlertRequest represents a request to resolve an alert
type ResolveAlertRequest struct {
	Resolution string `json:"resolution" binding:"required"`
}

// AcknowledgeAlertRequest represents a request to acknowledge an alert
type AcknowledgeAlertRequest struct {
	Note string `json:"note,omitempty"`
}

// AlertResponse represents the API response for an alert
type AlertResponse struct {
	ID             uuid.UUID      `json:"id"`
	FestivalID     uuid.UUID      `json:"festivalId"`
	UserID         *uuid.UUID     `json:"userId,omitempty"`
	Type           AlertType      `json:"type"`
	Severity       AlertSeverity  `json:"severity"`
	Status         AlertStatus    `json:"status"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	Location       AlertLocation  `json:"location"`
	ContactPhone   string         `json:"contactPhone,omitempty"`
	AssignedTo     *uuid.UUID     `json:"assignedTo,omitempty"`
	AcknowledgedAt *string        `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *uuid.UUID     `json:"acknowledgedBy,omitempty"`
	ResolvedAt     *string        `json:"resolvedAt,omitempty"`
	ResolvedBy     *uuid.UUID     `json:"resolvedBy,omitempty"`
	Resolution     string         `json:"resolution,omitempty"`
	Metadata       AlertMetadata  `json:"metadata"`
	CreatedAt      string         `json:"createdAt"`
	UpdatedAt      string         `json:"updatedAt"`
}

func (a *Alert) ToResponse() AlertResponse {
	resp := AlertResponse{
		ID:           a.ID,
		FestivalID:   a.FestivalID,
		UserID:       a.UserID,
		Type:         a.Type,
		Severity:     a.Severity,
		Status:       a.Status,
		Title:        a.Title,
		Description:  a.Description,
		Location:     a.Location,
		ContactPhone: a.ContactPhone,
		AssignedTo:   a.AssignedTo,
		AcknowledgedBy: a.AcknowledgedBy,
		ResolvedBy:   a.ResolvedBy,
		Resolution:   a.Resolution,
		Metadata:     a.Metadata,
		CreatedAt:    a.CreatedAt.Format(time.RFC3339),
		UpdatedAt:    a.UpdatedAt.Format(time.RFC3339),
	}

	if a.AcknowledgedAt != nil {
		formatted := a.AcknowledgedAt.Format(time.RFC3339)
		resp.AcknowledgedAt = &formatted
	}

	if a.ResolvedAt != nil {
		formatted := a.ResolvedAt.Format(time.RFC3339)
		resp.ResolvedAt = &formatted
	}

	return resp
}

// AlertStats represents statistics about alerts
type AlertStats struct {
	TotalAlerts      int64 `json:"totalAlerts"`
	PendingAlerts    int64 `json:"pendingAlerts"`
	InProgressAlerts int64 `json:"inProgressAlerts"`
	ResolvedAlerts   int64 `json:"resolvedAlerts"`
	CriticalAlerts   int64 `json:"criticalAlerts"`
	HighAlerts       int64 `json:"highAlerts"`
	AverageResponseTime float64 `json:"averageResponseTime"` // in seconds
}

// SecurityZoneResponse represents the API response for a security zone
type SecurityZoneResponse struct {
	ID          uuid.UUID     `json:"id"`
	FestivalID  uuid.UUID     `json:"festivalId"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Type        ZoneType      `json:"type"`
	Coordinates []Coordinate  `json:"coordinates"`
	Capacity    int           `json:"capacity,omitempty"`
	AlertLevel  AlertSeverity `json:"alertLevel"`
	IsActive    bool          `json:"isActive"`
	CreatedAt   string        `json:"createdAt"`
	UpdatedAt   string        `json:"updatedAt"`
}

func (z *SecurityZone) ToResponse() SecurityZoneResponse {
	return SecurityZoneResponse{
		ID:          z.ID,
		FestivalID:  z.FestivalID,
		Name:        z.Name,
		Description: z.Description,
		Type:        z.Type,
		Coordinates: z.Coordinates,
		Capacity:    z.Capacity,
		AlertLevel:  z.AlertLevel,
		IsActive:    z.IsActive,
		CreatedAt:   z.CreatedAt.Format(time.RFC3339),
		UpdatedAt:   z.UpdatedAt.Format(time.RFC3339),
	}
}

// CreateZoneRequest represents a request to create a security zone
type CreateZoneRequest struct {
	Name        string        `json:"name" binding:"required"`
	Description string        `json:"description"`
	Type        ZoneType      `json:"type" binding:"required"`
	Coordinates []Coordinate  `json:"coordinates" binding:"required"`
	Capacity    int           `json:"capacity,omitempty"`
}

// UpdateZoneRequest represents a request to update a security zone
type UpdateZoneRequest struct {
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Type        *ZoneType      `json:"type,omitempty"`
	Coordinates []Coordinate   `json:"coordinates,omitempty"`
	Capacity    *int           `json:"capacity,omitempty"`
	AlertLevel  *AlertSeverity `json:"alertLevel,omitempty"`
	IsActive    *bool          `json:"isActive,omitempty"`
}
