import { api } from '@/lib/api'

// Types for security alerts
export type AlertType = 'SOS' | 'MEDICAL' | 'FIRE' | 'THEFT' | 'VIOLENCE' | 'LOST_CHILD' | 'SUSPICIOUS' | 'CROWD_CONTROL' | 'OTHER'
export type AlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type AlertStatus = 'PENDING' | 'ACKNOWLEDGED' | 'IN_PROGRESS' | 'RESOLVED' | 'CANCELLED'

export interface AlertLocation {
  latitude: number
  longitude: number
  accuracy?: number
  zone?: string
  description?: string
}

export interface AlertMetadata {
  deviceInfo?: string
  appVersion?: string
  attachments?: string[]
  tags?: string[]
  priority?: number
  autoGenerated?: boolean
}

export interface SecurityAlert {
  id: string
  festivalId: string
  userId?: string
  type: AlertType
  severity: AlertSeverity
  status: AlertStatus
  title: string
  description: string
  location: AlertLocation
  contactPhone?: string
  assignedTo?: string
  acknowledgedAt?: string
  acknowledgedBy?: string
  resolvedAt?: string
  resolvedBy?: string
  resolution?: string
  metadata: AlertMetadata
  createdAt: string
  updatedAt: string
}

export interface AlertStats {
  totalAlerts: number
  pendingAlerts: number
  inProgressAlerts: number
  resolvedAlerts: number
  criticalAlerts: number
  highAlerts: number
  averageResponseTime: number
}

export interface SecurityZone {
  id: string
  festivalId: string
  name: string
  description: string
  type: 'GENERAL' | 'VIP' | 'STAGE' | 'CAMPING' | 'PARKING' | 'ENTRANCE' | 'MEDICAL' | 'RESTRICTED'
  coordinates: Array<{ latitude: number; longitude: number }>
  capacity?: number
  alertLevel: AlertSeverity
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface CreateAlertRequest {
  type: AlertType
  severity?: AlertSeverity
  title: string
  description?: string
  location?: AlertLocation
  contactPhone?: string
  metadata?: AlertMetadata
}

export interface UpdateAlertRequest {
  status?: AlertStatus
  severity?: AlertSeverity
  assignedTo?: string
  description?: string
  resolution?: string
}

export interface AlertFilters {
  type?: AlertType[]
  severity?: AlertSeverity[]
  status?: AlertStatus[]
  assignedTo?: string
  page?: number
  perPage?: number
}

export interface PaginatedResponse<T> {
  data: T[]
  meta: {
    total: number
    page: number
    per_page: number
  }
}

// API functions
export const securityApi = {
  // Get all alerts for a festival
  getAlerts: (festivalId: string, filters?: AlertFilters) => {
    const params = new URLSearchParams()
    if (filters?.type?.length) params.set('type', filters.type.join(','))
    if (filters?.severity?.length) params.set('severity', filters.severity.join(','))
    if (filters?.status?.length) params.set('status', filters.status.join(','))
    if (filters?.assignedTo) params.set('assigned_to', filters.assignedTo)
    if (filters?.page) params.set('page', String(filters.page))
    if (filters?.perPage) params.set('per_page', String(filters.perPage))

    const query = params.toString()
    return api.get<PaginatedResponse<SecurityAlert>>(
      `/api/v1/festivals/${festivalId}/security/alerts${query ? `?${query}` : ''}`
    )
  },

  // Get active alerts for a festival
  getActiveAlerts: (festivalId: string) =>
    api.get<SecurityAlert[]>(`/api/v1/festivals/${festivalId}/security/alerts/active`),

  // Get alert statistics
  getAlertStats: (festivalId: string) =>
    api.get<AlertStats>(`/api/v1/festivals/${festivalId}/security/alerts/stats`),

  // Get a specific alert
  getAlert: (festivalId: string, alertId: string) =>
    api.get<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}`),

  // Create a new alert
  createAlert: (festivalId: string, data: CreateAlertRequest) =>
    api.post<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts`, data),

  // Update an alert
  updateAlert: (festivalId: string, alertId: string, data: UpdateAlertRequest) =>
    api.patch<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}`, data),

  // Acknowledge an alert
  acknowledgeAlert: (festivalId: string, alertId: string) =>
    api.post<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}/acknowledge`),

  // Assign an alert
  assignAlert: (festivalId: string, alertId: string, assignedTo: string) =>
    api.post<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}/assign`, { assignedTo }),

  // Resolve an alert
  resolveAlert: (festivalId: string, alertId: string, resolution: string) =>
    api.post<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}/resolve`, { resolution }),

  // Cancel an alert
  cancelAlert: (festivalId: string, alertId: string, reason: string) =>
    api.post<SecurityAlert>(`/api/v1/festivals/${festivalId}/security/alerts/${alertId}/cancel`, { reason }),

  // Get security zones
  getZones: (festivalId: string) =>
    api.get<SecurityZone[]>(`/api/v1/festivals/${festivalId}/security/zones`),

  // Create a security zone
  createZone: (festivalId: string, data: Partial<SecurityZone>) =>
    api.post<SecurityZone>(`/api/v1/festivals/${festivalId}/security/zones`, data),

  // Update a security zone
  updateZone: (festivalId: string, zoneId: string, data: Partial<SecurityZone>) =>
    api.patch<SecurityZone>(`/api/v1/festivals/${festivalId}/security/zones/${zoneId}`, data),

  // Delete a security zone
  deleteZone: (festivalId: string, zoneId: string) =>
    api.delete(`/api/v1/festivals/${festivalId}/security/zones/${zoneId}`),
}

// Query keys for React Query
export const securityQueryKeys = {
  all: ['security'] as const,
  alerts: (festivalId: string) => [...securityQueryKeys.all, 'alerts', festivalId] as const,
  activeAlerts: (festivalId: string) => [...securityQueryKeys.all, 'activeAlerts', festivalId] as const,
  alertStats: (festivalId: string) => [...securityQueryKeys.all, 'stats', festivalId] as const,
  alert: (festivalId: string, alertId: string) => [...securityQueryKeys.all, 'alert', festivalId, alertId] as const,
  zones: (festivalId: string) => [...securityQueryKeys.all, 'zones', festivalId] as const,
}

// Helper functions
export function getAlertTypeLabel(type: AlertType): string {
  const labels: Record<AlertType, string> = {
    SOS: 'SOS',
    MEDICAL: 'Medical',
    FIRE: 'Incendie',
    THEFT: 'Vol',
    VIOLENCE: 'Violence',
    LOST_CHILD: 'Enfant perdu',
    SUSPICIOUS: 'Comportement suspect',
    CROWD_CONTROL: 'Controle foule',
    OTHER: 'Autre',
  }
  return labels[type] || type
}

export function getAlertTypeColor(type: AlertType): string {
  const colors: Record<AlertType, string> = {
    SOS: 'red',
    MEDICAL: 'orange',
    FIRE: 'red',
    THEFT: 'purple',
    VIOLENCE: 'red',
    LOST_CHILD: 'blue',
    SUSPICIOUS: 'yellow',
    CROWD_CONTROL: 'yellow',
    OTHER: 'gray',
  }
  return colors[type] || 'gray'
}

export function getSeverityLabel(severity: AlertSeverity): string {
  const labels: Record<AlertSeverity, string> = {
    LOW: 'Faible',
    MEDIUM: 'Moyen',
    HIGH: 'Eleve',
    CRITICAL: 'Critique',
  }
  return labels[severity] || severity
}

export function getSeverityColor(severity: AlertSeverity): string {
  const colors: Record<AlertSeverity, string> = {
    LOW: 'gray',
    MEDIUM: 'yellow',
    HIGH: 'orange',
    CRITICAL: 'red',
  }
  return colors[severity] || 'gray'
}

export function getStatusLabel(status: AlertStatus): string {
  const labels: Record<AlertStatus, string> = {
    PENDING: 'En attente',
    ACKNOWLEDGED: 'Pris en compte',
    IN_PROGRESS: 'En cours',
    RESOLVED: 'Resolu',
    CANCELLED: 'Annule',
  }
  return labels[status] || status
}

export function getStatusColor(status: AlertStatus): string {
  const colors: Record<AlertStatus, string> = {
    PENDING: 'red',
    ACKNOWLEDGED: 'yellow',
    IN_PROGRESS: 'blue',
    RESOLVED: 'green',
    CANCELLED: 'gray',
  }
  return colors[status] || 'gray'
}
